server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: washer-service
          uri: lb://WASHER-SERVICE
          predicates:
            - Path=/washer/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
