server:
  port: 8081

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:mysql://localhost:3306/admin_db
    username: root
    password: Ayush8923

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
